# Generated by Django 3.0.7 on 2020-06-08 12:45

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ('subcategory__name', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Category')),
            ],
            options={
                'ordering': ('category__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995)], default=2021, validators=[django.core.validators.MinValueValidator(1995), exam.models.max_value_current_year])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Board')),
            ],
            options={
                'ordering': ('-year', 'board__name'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('question_body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option1', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option2', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option3', ckeditor_uploader.fields.RichTextUploadingField()),
                ('option4', ckeditor_uploader.fields.RichTextUploadingField()),
                ('answer_number', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('solution', ckeditor_uploader.fields.RichTextUploadingField()),
                ('chapters', models.ManyToManyField(to='exam.Chapter')),
                ('histories', models.ManyToManyField(blank=True, to='exam.QuestionHistory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Language')),
                ('subcategories', models.ManyToManyField(to='exam.SubCategory')),
                ('types', models.ManyToManyField(to='exam.QuestionType')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.SubCategory'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('name', 'subcategory'), name='chapter constraint'),
        ),
    ]
