# Generated by Django 3.0.7 on 2020-06-06 19:49

import django.core.validators
from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200607_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionhistory',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1995), exam.models.max_value_current_year]),
        ),
    ]
