# Generated by Django 3.0.7 on 2020-06-06 19:51

import django.core.validators
from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20200607_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionhistory',
            name='year',
            field=models.PositiveIntegerField(choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995)], default=2021, validators=[django.core.validators.MinValueValidator(1995), exam.models.max_value_current_year]),
        ),
    ]
