# Generated by Django 3.0.7 on 2020-06-06 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_question_solution_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution_number',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
