# Generated by Django 3.0.7 on 2020-06-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20200607_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='solution_number',
            new_name='answer_number',
        ),
    ]
