# Generated by Django 3.0.7 on 2020-06-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20200607_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='histories',
            field=models.ManyToManyField(blank=True, to='exam.QuestionHistory'),
        ),
    ]
