# Generated by Django 3.0.7 on 2020-06-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20200607_0436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('subcategory__name', 'number')},
        ),
        migrations.AlterModelOptions(
            name='questionhistory',
            options={'ordering': ('-year', 'board__name')},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('category__name', 'name')},
        ),
    ]
