# Generated by Django 3.0.7 on 2020-08-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_subcategory_time_in_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigotoBochor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='bigotobochor')),
                ('question_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.QuestionHistory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SubCategory')),
            ],
        ),
    ]
