# Generated by Django 3.0.7 on 2020-08-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigoto_bochor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigotobochor',
            options={'ordering': ('-question_history__year', 'question_history__board__name', 'subcategory__name'), 'verbose_name': 'বিগত বছর', 'verbose_name_plural': 'বিগত বছর'},
        ),
    ]
