# Generated by Django 3.0.7 on 2020-07-23 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_auto_20200724_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('subcategories', models.ManyToManyField(to='common.SubCategory')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
    ]
