# Generated by Django 3.0.7 on 2020-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200724_1636'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='notification',
            name='categories',
            field=models.ManyToManyField(blank=True, to='common.Category'),
        ),
    ]
