# Generated by Django 3.0.7 on 2020-08-11 09:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200725_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
