# Generated by Django 3.0.7 on 2020-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_board_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('subcategory__name', 'name')},
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('name', 'subcategory'), name='board constraint'),
        ),
    ]
