# Generated by Django 3.0.7 on 2020-07-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200708_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='mark_of_correct_mcq_question',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='negative_mark_of_incorrect_question',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='number_of_questions_for_mcq_exam',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
