# Generated by Django 3.0.7 on 2020-10-01 12:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0003_auto_20200724_0025'),
        ('common', '0006_subcategory_time_in_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicVitticPorashona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True)),
                ('topic_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('cover_img', models.ImageField(upload_to='shop/cover')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('chapters', models.ManyToManyField(to='common.Chapter')),
                ('questions', models.ManyToManyField(to='question.McqQuestion')),
                ('subcategories', models.ManyToManyField(blank=True, to='common.SubCategory')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('topic_number',),
            },
        ),
    ]
