# Generated by Django 3.0.7 on 2020-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_subcategory_time_in_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_img', models.FileField(upload_to='boi_porichiti/cover')),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='boi_porichiti/pdf')),
                ('subcategories', models.ManyToManyField(blank=True, to='common.SubCategory')),
            ],
            options={
                'verbose_name': 'বই পরিচিতি',
                'verbose_name_plural': 'বই পরিচিতি',
                'ordering': ('title',),
            },
        ),
    ]
