# Generated by Django 3.0.7 on 2020-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi_porichiti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='boi_porichiti/pdf'),
        ),
    ]
