# Generated by Django 3.0.7 on 2020-09-16 09:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi_porichiti', '0002_auto_20200916_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boi',
            name='cover_img',
            field=models.ImageField(upload_to='boi_porichiti/cover'),
        ),
        migrations.AlterField(
            model_name='boi',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
