# Generated by Django 3.0.7 on 2020-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi_porichiti', '0003_auto_20200916_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='boi',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
