# Generated by Django 3.0.7 on 2020-07-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200708_1326'),
        ('question', '0002_auto_20200708_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='McqQuestion',
        ),
    ]
