# Generated by Django 3.0.7 on 2020-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goniter_itihash', '0002_auto_20200916_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='goniteritihash',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
