# Generated by Django 3.0.7 on 2020-09-16 09:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0006_subcategory_time_in_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_img', models.ImageField(upload_to='shop/cover')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='shop/pdf')),
                ('subcategories', models.ManyToManyField(blank=True, to='common.SubCategory')),
            ],
            options={
                'verbose_name': 'দোকান',
                'verbose_name_plural': 'দোকান',
                'ordering': ('title',),
            },
        ),
    ]
