# Generated by Django 3.0.7 on 2020-07-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_sub_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
