# Generated by Django 3.0.7 on 2020-06-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200607_0120'),
        ('user_profile', '0004_auto_20200606_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.Category'),
        ),
    ]
