# Generated by Django 3.0.7 on 2020-10-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_subcategory_time_in_minute'),
        ('user_profile', '0005_auto_20201005_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_level',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.SubCategory'),
        ),
    ]
