# Generated by Django 3.0.7 on 2020-06-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200607_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('name',)},
        ),
    ]
